### ISSUE TITLE
Game page of old games shows null hash.

### ISSUE THREAD

**Issue by kungfuant** [moneypot/webserver#128]
The game page https://www.moneypot.com/game/XXXXXX shows "Hash: null" instead of the proper hash for games that happened before the switch to the provably fair distribution.

![screen shot 2015-01-21 at 03 15 43](https://cloud.githubusercontent.com/assets/8939884/5830104/cfa386f4-a11b-11e4-8737-c2a4f027b8ff.png)

**Comment by rakeshok** [comment]
We think that its better not to support old games, and drop the seed column from the database.
