### ISSUE TITLE
Introduce stopping conditions for AutoBet

### ISSUE THREAD

**Issue by kungfuant** [moneypot/webserver#129]
It would be nice to tell the AutoBet strategy to stop when a certain bet limit has been reached, so that it doesn't gamble away all the balance of an account. This seems critical now that the max-bet has been increased to 1 BTC.

Another option would be to limit on the balance as is done on a couple of sites: Don't bet if the wager would take the balance below X.

**Comment by kungfuant** [comment]
Duplicate of #130.

**Comment by RHavar** [comment]
Ah sorry about duplicating it, I created #130 before I saw this. This is a much better written issue, so I'll use it. =)

**Comment by rakeshok** [comment]
done :), the limit on the wager multiplier could be done with a few javascript lines in the strategy script

**Comment by rakeshok** [comment]
done :), the limit on the wager multiplier could be done with a few javascript lines in the strategy script
