### ISSUE TITLE
Broken schema

### ISSUE THREAD

**Issue by kungfuant** [moneypot/webserver#139]
Starting with c391b272ab6d25f995d5be515bfac1f0122e3d78, creating the DB with the schema fails with  

psql:server/schema.sql:274: ERROR:  column "u.username" must appear in the GROUP BY clause or be used in an aggregate function
LINE 4:             u.username,

**Comment by kungfuant** [comment]
$ psql --version
psql (PostgreSQL) 9.4.0

**Comment by RHavar** [comment]
Thanks! The view was created before the things it depends on. Moving to end of the file
