### ISSUE TITLE
Wrong bonus shown in game history on instant crashes

### ISSUE THREAD

**Issue by kungfuant** [moneypot/webserver#150]
Players should be awarded 0% bonus on 0x crashes but the client shows 1% bonus.

![650a3d92bd8530001db8f232cda0015a](https://cloud.githubusercontent.com/assets/8939884/6030066/2342121a-abf5-11e4-9ee7-e03a0a866c79.png)

**Comment by RHavar** [comment]
Ah thanks, nice catch
